In [61]:
from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier  # classification algorithm
from sklearn.model_selection import cross_val_score, KFold
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [62]:
def sklearn_to_df(sklearn_dataset):
    df = pd.DataFrame(sklearn_dataset.data, columns=sklearn_dataset.feature_names)
    df['target'] = pd.Series(sklearn_dataset.target)
    return df
wine = load_wine()
df_wine = sklearn_to_df(wine)
df_wine.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [63]:
df_wine.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'target'],
      dtype='object')

In [64]:
X = df_wine.iloc[:, :-1].values
y = df_wine.iloc[:, -1].values

In [65]:
kf = KFold(n_splits=10, shuffle=True, random_state=0)

In [66]:
for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train, X_test, y_train, y_test)

TRAIN: [  0   1   2   3   4   6   8   9  10  11  12  13  14  15  16  17  19  20
  21  22  23  24  25  26  27  28  29  30  31  32  34  35  36  37  38  39
  40  41  42  43  44  45  46  47  48  49  50  51  52  53  56  57  58  59
  60  61  62  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
  79  81  82  83  84  85  86  87  88  89  91  92  93  94  95  96  97  99
 100 101 102 103 104 105 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 122 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138
 139 140 142 143 144 145 147 148 149 150 152 153 154 155 156 157 158 159
 161 162 163 164 165 166 167 169 170 171 172 173 174 175 176 177] TEST: [  5   7  18  33  54  55  63  80  90  98 106 121 123 141 146 151 160 168]
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8

In [67]:
scores = cross_val_score(RandomForestClassifier(n_estimators=50), X, y, cv=kf, scoring='accuracy', n_jobs=-1, verbose=1)
scores

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   6 out of  10 | elapsed:    3.6s remaining:    2.4s
[Parallel(n_jobs=-1)]: Done  10 out of  10 | elapsed:    3.7s finished


array([0.94444444, 0.94444444, 1.        , 0.94444444, 0.94444444,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [68]:
print("%f accuracy with a standard deviation of %f" % (scores.mean(), scores.std()))

0.977778 accuracy with a standard deviation of 0.027217
